<?php

/**
 * @file
 * Contains \Drupal\convert_nodes\convert_nodes.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function convert_nodes_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the convert_nodes module.
    case 'help.page.convert_nodes':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The convert nodes module provides a UI to convert drupal8 nodes from one content type to another') . '</p>';
      return $output;
  }
}
